language: elixir
elixir:
  - 1.11.2
otp_release:
  - 23.0

script:
  - mix test
  - mix format --check-formatted

before_install:
  - rvm install 2.3.1
  - rvm use 2.3.1
  - gem install liquid -v 4.0.2
script:
  - MIX_ENV=test mix test --trace
sudo: false
